### PR TITLE
add support for prop-types-extra

### PR DESCRIPTION
**Pull request by ericvergnaud**
add support for legacy prop-types-extra for old packages such as react-bootstrap < 1

### CODE REVIEW

**Comment by ericvergnaud** [comment]
@markalfred hi
I'm taking the liberty to propose an enrichment
all tests pass locally but the build fails
looks like the CI config is no longer supported by travis

**Comment by ericvergnaud** [comment]
all green!

**Comment by ericvergnaud** [comment]
n.b.: the build was not broken, seems my local install was polluted hence the difference in behavior

**Comment by markalfred** [comment]
Hi @ericvergnaud, thank you for all the great work you did here. I was away for a few weeks but I'm looking over this PR now, it looks like a great addition to this project, and it aligns with a longer-term goal that I have for it, noted in issue #1

Let me think about some of the implications of this and I'll note my thoughts in the PR shortly, thank you again for taking this on!

**Comment by markalfred** [comment]
Hey @ericvergnaud, the biggest thing I'm thinking is that, rather than extending the library's current export, maybe prop-types-extra can be a nested export. That would keep the original library "clean" in that it would remain a drop-in-repacement for `react/prop-types`, and would also allow for additional prop-type libraries to be supported in the future without complicating things.

In short...
```ts
// Rather than:
import { PropTypes, PropTypesExtra } from 'introspective-prop-types'

// Do this:
import PropTypes from 'introspective-prop-types'
import PropTypesExtra from 'introspective-prop-types/extra'
```

I'm experimenting with this change now and I'll push it up when I'm done, but I wanted to get your thoughts on whether this would work for your usecase.

Thanks again for all the work you did here, I think it also sets the layout for adding additional prop-type libraries to this one. 🙇

**Comment by markalfred** [comment]
I added a few commits and changed around one of the tests, and it looks like this might be a "real" issue, so I'm looking into it now. Let me know if you have any thoughts on any of the changes I've made.

**Comment by ericvergnaud** [comment]
Hi,

no problem with that.

Eric

**Comment by markalfred** [comment]
It looks like the source of the issue was that everything in the library was designed around the shape of the proptypes in the prop-types library:

1. Every proptype takes zero or one arguments
2. Every base proptype has an `.isRequired` version of itself

Since these things aren't true of all the proptypes in prop-types-extra, it caused a bunch of issues. I adjusted some of the "common" code and tests, as well as some of the logic in the prop-types-extra handler, to account for these differences.

Thanks again @ericvergnaud, I really appreciate you contributing to this project!

**Pull request merged**
